### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr-gson#1]
Hi @before,

great to have you onboard :)

In a first step we should setup the javaslang-gson repository first an initial commit.

You may take the javaslang-jackson project as template. It is a Maven layout. Or you may choose Gradle for the build - your call.

Please ask on any questions - I will assist you whenever possible.

Greets

\- Daniel

**Comment by danieldietrich** [comment]
@before I realized that I messed it up to setup the project on Github. Now you have write permission to the repository. Do you need any assistance (initial directory structure)?

**Comment by arouel** [comment]
@danieldietrich I haven't had a chance to look at it yet. I thought I start with a quick Gradle setup, pull in JavaSlang and GSON as dependencies and start writing test cases and implementation. Would that be fine for you or are you sticked to Maven?

**Comment by danieldietrich** [comment]
@before that would be perfectly fine! We also plan a transition from Maven to Gradle in our core project.
